[workspace]
members = [
    # core engine that runs the other applications
    "engine",

    # demos: test or show engine tech
    "d1", # demo: initial engine implementation
    "d2", # demo: 2d textures
]
resolver="1"
