use std::fmt::{Display, Formatter};

#[derive(Debug, Clone, Eq, Hash, PartialEq)]
pub enum KeyInputName {
    KeyEscape,
    KeyTilde,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    Key0,
    KeyA,
    KeyB,
    KeyC,
    KeyD,
    KeyE,
    KeyF,
    KeyG,
    KeyH,
    KeyI,
    KeyJ,
    KeyK,
    KeyL,
    KeyM,
    KeyN,
    KeyO,
    KeyP,
    KeyQ,
    KeyR,
    KeyS,
    KeyT,
    KeyU,
    KeyV,
    KeyW,
    KeyX,
    KeyY,
    KeyZ,
}

impl Display for KeyInputName {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            KeyInputName::KeyEscape => write!(f, "esc"),
            KeyInputName::KeyTilde => write!(f, "tilde"),
            KeyInputName::Key1 => write!(f, "1"),
            KeyInputName::Key2 => write!(f, "2"),
            KeyInputName::Key3 => write!(f, "3"),
            KeyInputName::Key4 => write!(f, "4"),
            KeyInputName::Key5 => write!(f, "5"),
            KeyInputName::Key6 => write!(f, "6"),
            KeyInputName::Key7 => write!(f, "7"),
            KeyInputName::Key8 => write!(f, "8"),
            KeyInputName::Key9 => write!(f, "9"),
            KeyInputName::Key0 => write!(f, "0"),
            KeyInputName::KeyA => write!(f, "{}", "KeyA"),
            KeyInputName::KeyB => write!(f, "{}", "KeyB"),
            KeyInputName::KeyC => write!(f, "{}", "KeyC"),
            KeyInputName::KeyD => write!(f, "{}", "KeyD"),
            KeyInputName::KeyE => write!(f, "{}", "KeyE"),
            KeyInputName::KeyF => write!(f, "{}", "KeyF"),
            KeyInputName::KeyG => write!(f, "{}", "KeyG"),
            KeyInputName::KeyH => write!(f, "{}", "KeyH"),
            KeyInputName::KeyI => write!(f, "{}", "KeyI"),
            KeyInputName::KeyJ => write!(f, "{}", "KeyJ"),
            KeyInputName::KeyK => write!(f, "{}", "KeyK"),
            KeyInputName::KeyL => write!(f, "{}", "KeyL"),
            KeyInputName::KeyM => write!(f, "{}", "KeyM"),
            KeyInputName::KeyN => write!(f, "{}", "KeyN"),
            KeyInputName::KeyO => write!(f, "{}", "KeyO"),
            KeyInputName::KeyP => write!(f, "{}", "KeyP"),
            KeyInputName::KeyQ => write!(f, "{}", "KeyQ"),
            KeyInputName::KeyR => write!(f, "{}", "KeyR"),
            KeyInputName::KeyS => write!(f, "{}", "KeyS"),
            KeyInputName::KeyT => write!(f, "{}", "KeyT"),
            KeyInputName::KeyU => write!(f, "{}", "KeyU"),
            KeyInputName::KeyV => write!(f, "{}", "KeyV"),
            KeyInputName::KeyW => write!(f, "{}", "KeyW"),
            KeyInputName::KeyX => write!(f, "{}", "KeyX"),
            KeyInputName::KeyY => write!(f, "{}", "KeyY"),
            KeyInputName::KeyZ => write!(f, "{}", "KeyZ"),
        }
    }
}
